In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [7]:
df = pd.read_csv("train.csv", usecols=["Survived", "Pclass", "Age", "Fare"])

In [8]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [10]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [11]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43)

In [13]:
X_train.head()

     Pclass   Age      Fare
826       3   NaN   56.4958
838       3  32.0   56.4958
763       1  36.0  120.0000
189       3  36.0    7.8958
109       3   NaN   24.1500

In [88]:
knn = KNNImputer(n_neighbors=4, weights="distance") # default weights are uniform

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [89]:
X_train_trf

array([[  3.    ,  29.5   ,  56.4958],
       [  3.    ,  32.    ,  56.4958],
       [  1.    ,  36.    , 120.    ],
       ...,
       [  3.    ,  29.    ,  15.2458],
       [  3.    ,  22.    ,   7.25  ],
       [  3.    ,  21.    ,   8.6625]])

In [90]:
pd.DataFrame(X_train_trf, columns=X_train.columns).head()

   Pclass    Age      Fare
0     3.0  29.50   56.4958
1     3.0  32.00   56.4958
2     1.0  36.00  120.0000
3     3.0  36.00    7.8958
4     3.0  25.75   24.1500

In [91]:
lr = LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test, y_pred)

0.6927374301675978

In [93]:
# comaprison with simpleimputer >> mean

In [96]:
si = SimpleImputer()

X_train_tr = si.fit_transform(X_train)
X_test_tr = si.transform(X_test)

In [97]:
lr = LogisticRegression()

lr.fit(X_train_tr, y_train)

y_pred = lr.predict(X_test_tr)

accuracy_score(y_test, y_pred)

0.6815642458100558