In [1]:
import pandas as pd
import numpy as np

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [5]:
df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"], inplace=True)

In [6]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [11]:
X_train, X_test, y_train, y_test = train_test_split(df.drop("Survived", axis =1), df["Survived"], test_size = 0.2, random_state=0)

In [16]:
print(X_train.shape)
X_train.head(3)

(712, 7)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C

In [13]:
X_test.shape

(179, 7)

In [33]:
X_train["Embarked"].value_counts()

Embarked
S    517
C    129
Q     64
Name: count, dtype: int64

In [17]:
print(y_train.shape)
y_train.head()

(712,)

140    0
439    0
817    0
378    0
491    0
Name: Survived, dtype: int64

In [25]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [35]:
# applying imputation on missing values column
si_age = SimpleImputer()
si_emb = SimpleImputer(strategy="most_frequent")

X_train_age = si_age.fit_transform(X_train[["Age"]])
X_train_emb = si_emb.fit_transform(X_train[["Embarked"]])

X_test_age = si_age.transform(X_test[["Age"]])
X_test_emb = si_emb.transform(X_test[["Embarked"]])

In [37]:
X_train_age

array([[29.74518389],
       [31.        ],
       [31.        ],
       [20.        ],
       [21.        ],
       [45.5       ],
       [22.        ],
       [29.74518389],
       [29.74518389],
       [26.        ],
       [25.        ],
       [21.        ],
       [31.        ],
       [15.        ],
       [29.74518389],
       [29.74518389],
       [65.        ],
       [29.74518389],
       [ 1.        ],
       [34.        ],
       [49.        ],
       [18.        ],
       [29.74518389],
       [70.        ],
       [14.        ],
       [19.        ],
       [30.        ],
       [31.        ],
       [32.        ],
       [16.        ],
       [50.        ],
       [24.        ],
       [56.        ],
       [ 7.        ],
       [ 9.        ],
       [33.        ],
       [19.        ],
       [32.5       ],
       [ 1.        ],
       [45.        ],
       [29.74518389],
       [19.        ],
       [21.        ],
       [ 4.        ],
       [28.        ],
       [17.        ],
       [30.        ],
       [22.        ],
       [45.        ],
       [25.        ],
       [18.        ],
       [33.        ],
       [24.        ],
       [26.        ],
       [22.        ],
       [56.        ],
       [28.        ],
       [35.        ],
       [ 6.        ],
       [41.        ],
       [29.74518389],
       [29.74518389],
       [52.        ],
       [32.        ],
       [35.        ],
       [18.        ],
       [29.74518389],
       [29.74518389],
       [29.74518389],
       [29.74518389],
       [27.        ],
       [22.        ],
       [16.        ],
       [49.        ],
       [29.74518389],
       [16.        ],
       [18.        ],
       [29.74518389],
       [45.        ],
       [ 3.        ],
       [70.5       ],
       [29.74518389],
       [29.74518389],
       [34.5       ],
       [40.        ],
       [29.74518389],
       [27.        ],
       [18.        ],
       [29.74518389],
       [51.        ],
       [49.        ],
       [ 1.        ],
       [54.        ],
       [29.74518389],
       [ 8.        ],
       [24.        ],
       [20.        ],
       [30.        ],
       [24.        ],
       [29.74518389],
       [29.74518389],
       [25.        ],
       [29.74518389],
       [29.74518389],
       [48.        ],
       [74.        ],
       [23.        ],
       [17.        ],
       [29.74518389],
       [52.        ],
       [29.74518389],
       [29.74518389],
       [34.        ],
       [29.74518389],
       [34.        ],
       [24.        ],
       [29.        ],
       [36.        ],
       [61.        ],
       [45.        ],
       [34.        ],
       [29.74518389],
       [21.        ],
       [29.74518389],
       [ 0.83      ],
       [26.        ],
       [29.74518389],
       [55.        ],
       [ 6.        ],
       [50.        ],
       [26.        ],
       [34.        ],
       [39.        ],
       [30.        ],
       [29.74518389],
       [22.        ],
       [35.        ],
       [42.        ],
       [29.        ],
       [29.74518389],
       [31.        ],
       [29.74518389],
       [29.74518389],
       [41.        ],
       [28.        ],
       [46.        ],
       [29.74518389],
       [50.        ],
       [38.        ],
       [11.        ],
       [20.        ],
       [35.        ],
       [39.        ],
       [ 9.        ],
       [19.        ],
       [40.        ],
       [38.        ],
       [22.        ],
       [65.        ],
       [60.        ],
       [47.        ],
       [29.74518389],
       [51.        ],
       [21.        ],
       [27.        ],
       [27.        ],
       [49.        ],
       [29.        ],
       [16.        ],
       [21.        ],
       [47.        ],
       [58.        ],
       [40.        ],
       [35.        ],
       [51.        ],
       [27.        ],
       [33.        ],
       [ 4.        ],
       [28.        ],
       [34.        ],
       [43.        ],
       [29.74518389],
       [29.74518389],
       [39.        ],
       [29.74518389],
       [18.        ],
       [30.        ],
       [23.        ],
       [16.        ],
       [26.        ],
       [30.        ],
       [18.        ],
       [ 8.        ],
       [55.        ],
       [44.        ],
       [29.74518389],
       [54.        ],
       [30.        ],
       [20.        ],
       [ 2.        ],
       [37.        ],
       [29.74518389],
       [29.74518389],
       [16.        ],
       [19.        ],
       [21.        ],
       [29.        ],
       [29.74518389],
       [29.74518389],
       [15.        ],
       [ 3.        ],
       [29.74518389],
       [32.        ],
       [32.        ],
       [29.        ],
       [29.74518389],
       [48.        ],
       [ 2.        ],
       [23.        ],
       [32.        ],
       [29.        ],
       [28.5       ],
       [29.74518389],
       [29.74518389],
       [44.        ],
       [26.        ],
       [21.        ],
       [36.        ],
       [47.        ],
       [ 5.        ],
       [21.        ],
       [30.        ],
       [28.        ],
       [26.        ],
       [29.        ],
       [29.74518389],
       [24.        ],
       [32.        ],
       [29.74518389],
       [71.        ],
       [71.        ],
       [29.74518389],
       [41.        ],
       [36.        ],
       [32.        ],
       [24.        ],
       [18.        ],
       [36.        ],
       [33.        ],
       [22.        ],
       [29.74518389],
       [ 4.        ],
       [28.        ],
       [24.        ],
       [36.        ],
       [29.        ],
       [29.74518389],
       [57.        ],
       [29.        ],
       [39.        ],
       [29.74518389],
       [44.        ],
       [36.        ],
       [ 1.        ],
       [21.        ],
       [61.        ],
       [38.        ],
       [30.        ],
       [47.        ],
       [24.        ],
       [27.        ],
       [25.        ],
       [21.        ],
       [19.        ],
       [12.        ],
       [23.        ],
       [29.74518389],
       [20.        ],
       [ 4.        ],
       [40.        ],
       [14.        ],
       [30.        ],
       [17.        ],
       [38.        ],
       [29.74518389],
       [57.        ],
       [53.        ],
       [18.        ],
       [29.74518389],
       [26.        ],
       [51.        ],
       [40.        ],
       [35.        ],
       [25.        ],
       [36.        ],
       [28.        ],
       [35.        ],
       [29.74518389],
       [20.        ],
       [29.74518389],
       [24.        ],
       [33.        ],
       [18.        ],
       [34.        ],
       [18.        ],
       [47.        ],
       [30.        ],
       [19.        ],
       [22.        ],
       [25.        ],
       [29.74518389],
       [24.        ],
       [36.        ],
       [38.        ],
       [45.        ],
       [10.        ],
       [19.        ],
       [41.        ],
       [35.        ],
       [17.        ],
       [29.74518389],
       [20.        ],
       [29.74518389],
       [ 4.        ],
       [35.        ],
       [29.74518389],
       [22.        ],
       [40.        ],
       [ 8.        ],
       [25.        ],
       [18.        ],
       [22.        ],
       [25.        ],
       [32.        ],
       [29.74518389],
       [50.        ],
       [47.        ],
       [80.        ],
       [37.        ],
       [ 2.        ],
       [29.74518389],
       [33.        ],
       [20.        ],
       [16.        ],
       [ 3.        ],
       [29.74518389],
       [25.        ],
       [40.5       ],
       [25.        ],
       [46.        ],
       [29.74518389],
       [23.        ],
       [21.        ],
       [39.        ],
       [23.        ],
       [29.74518389],
       [39.        ],
       [29.74518389],
       [16.        ],
       [29.74518389],
       [39.        ],
       [29.74518389],
       [38.        ],
       [35.        ],
       [17.        ],
       [29.        ],
       [11.        ],
       [29.        ],
       [29.74518389],
       [29.74518389],
       [30.5       ],
       [52.        ],
       [21.        ],
       [24.        ],
       [24.        ],
       [29.74518389],
       [30.        ],
       [29.74518389],
       [16.        ],
       [ 3.        ],
       [22.        ],
       [35.        ],
       [27.        ],
       [48.        ],
       [15.        ],
       [29.74518389],
       [17.        ],
       [29.74518389],
       [25.        ],
       [30.        ],
       [ 0.83      ],
       [45.        ],
       [29.74518389],
       [29.74518389],
       [28.        ],
       [28.        ],
       [21.        ],
       [33.        ],
       [39.        ],
       [54.        ],
       [29.        ],
       [45.        ],
       [44.        ],
       [29.74518389],
       [29.74518389],
       [32.        ],
       [20.        ],
       [58.        ],
       [19.        ],
       [45.        ],
       [ 1.        ],
       [21.        ],
       [ 2.        ],
       [19.        ],
       [31.        ],
       [36.        ],
       [16.        ],
       [ 9.        ],
       [25.        ],
       [31.        ],
       [34.        ],
       [32.        ],
       [26.        ],
       [17.        ],
       [28.        ],
       [31.        ],
       [29.74518389],
       [44.        ],
       [ 4.        ],
       [18.        ],
       [23.        ],
       [33.        ],
       [30.        ],
       [48.        ],
       [38.        ],
       [26.        ],
       [24.        ],
       [26.        ],
       [ 2.        ],
       [27.        ],
       [ 2.        ],
       [27.        ],
       [22.        ],
       [29.74518389],
       [17.        ],
       [28.        ],
       [29.74518389],
       [29.74518389],
       [29.74518389],
       [29.74518389],
       [29.74518389],
       [22.        ],
       [36.        ],
       [18.        ],
       [18.        ],
       [25.        ],
       [36.        ],
       [19.        ],
       [13.        ],
       [16.        ],
       [41.        ],
       [29.74518389],
       [26.        ],
       [18.        ],
       [ 6.        ],
       [59.        ],
       [48.        ],
       [66.        ],
       [23.        ],
       [19.        ],
       [24.        ],
       [38.        ],
       [29.74518389],
       [24.        ],
       [32.        ],
       [29.74518389],
       [24.        ],
       [ 2.        ],
       [26.        ],
       [23.        ],
       [29.74518389],
       [32.        ],
       [ 9.        ],
       [34.        ],
       [36.        ],
       [30.        ],
       [36.        ],
       [42.        ],
       [22.        ],
       [48.        ],
       [21.        ],
       [43.        ],
       [29.74518389],
       [21.        ],
       [16.        ],
       [22.        ],
       [34.        ],
       [19.        ],
       [70.        ],
       [24.        ],
       [30.5       ],
       [24.        ],
       [19.        ],
       [ 8.        ],
       [ 1.        ],
       [27.        ],
       [45.        ],
       [42.        ],
       [14.5       ],
       [29.74518389],
       [26.        ],
       [64.        ],
       [29.74518389],
       [29.74518389],
       [56.        ],
       [52.        ],
       [29.74518389],
       [40.5       ],
       [22.        ],
       [ 0.75      ],
       [61.        ],
       [29.74518389],
       [29.74518389],
       [18.        ],
       [31.        ],
       [36.        ],
       [ 4.        ],
       [29.        ],
       [29.74518389],
       [38.        ],
       [47.        ],
       [42.        ],
       [55.5       ],
       [39.        ],
       [44.        ],
       [42.        ],
       [34.        ],
       [29.74518389],
       [24.        ],
       [29.74518389],
       [22.        ],
       [42.        ],
       [37.        ],
       [36.        ],
       [29.74518389],
       [27.        ],
       [29.74518389],
       [31.        ],
       [23.5       ],
       [35.        ],
       [19.        ],
       [59.        ],
       [47.        ],
       [31.        ],
       [65.        ],
       [30.        ],
       [29.74518389],
       [29.74518389],
       [29.74518389],
       [ 4.        ],
       [18.        ],
       [29.74518389],
       [31.        ],
       [63.        ],
       [62.        ],
       [ 9.        ],
       [29.74518389],
       [22.        ],
       [17.        ],
       [58.        ],
       [ 3.        ],
       [16.        ],
       [29.74518389],
       [47.        ],
       [ 5.        ],
       [27.        ],
       [29.74518389],
       [28.        ],
       [40.        ],
       [36.5       ],
       [29.74518389],
       [37.        ],
       [32.5       ],
       [23.        ],
       [16.        ],
       [34.        ],
       [27.        ],
       [33.        ],
       [42.        ],
       [28.        ],
       [29.74518389],
       [62.        ],
       [25.        ],
       [36.        ],
       [35.        ],
       [29.74518389],
       [29.74518389],
       [22.        ],
       [39.        ],
       [36.        ],
       [36.        ],
       [31.        ],
       [29.74518389],
       [30.        ],
       [42.        ],
       [29.74518389],
       [44.        ],
       [21.        ],
       [28.        ],
       [39.        ],
       [ 0.92      ],
       [29.74518389],
       [22.        ],
       [33.        ],
       [16.        ],
       [20.5       ],
       [50.        ],
       [19.        ],
       [29.74518389],
       [20.        ],
       [30.        ],
       [29.74518389],
       [54.        ],
       [29.74518389],
       [45.5       ],
       [17.        ],
       [29.74518389],
       [24.        ],
       [29.74518389],
       [23.        ],
       [20.        ],
       [29.74518389],
       [28.        ],
       [43.        ],
       [ 2.        ],
       [19.        ],
       [28.5       ],
       [27.        ],
       [30.        ],
       [20.        ],
       [25.        ],
       [29.74518389],
       [26.        ],
       [29.74518389],
       [29.74518389],
       [37.        ],
       [28.        ],
       [30.        ],
       [17.        ],
       [29.        ],
       [15.        ],
       [29.74518389],
       [11.        ],
       [29.74518389],
       [ 1.        ],
       [29.74518389],
       [29.        ],
       [18.        ],
       [22.        ],
       [30.        ],
       [52.        ],
       [32.        ],
       [50.        ],
       [29.74518389],
       [29.74518389],
       [36.        ],
       [42.        ],
       [28.        ],
       [ 9.        ],
       [58.        ],
       [31.        ],
       [24.        ],
       [50.        ],
       [34.        ],
       [ 4.        ],
       [ 5.        ],
       [29.74518389],
       [35.        ],
       [29.74518389],
       [ 0.67      ],
       [21.        ],
       [ 5.        ],
       [21.        ],
       [42.        ],
       [30.        ],
       [18.        ],
       [29.74518389],
       [28.        ],
       [56.        ],
       [29.74518389],
       [27.        ],
       [35.        ],
       [39.        ],
       [43.        ],
       [31.        ],
       [24.        ],
       [33.        ],
       [32.        ],
       [49.        ],
       [27.        ],
       [48.        ],
       [29.74518389],
       [50.        ],
       [14.        ],
       [29.74518389],
       [42.        ],
       [36.        ],
       [39.        ],
       [19.        ],
       [29.74518389],
       [36.        ],
       [60.        ]])

In [39]:
# applying onehotencoding on nominal categorical columns
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
ohe_emb = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

X_train_sex = ohe_sex.fit_transform(X_train[["Sex"]])
X_train_embarked = ohe_emb.fit_transform(X_train_emb)

X_test_sex = ohe_sex.transform(X_test[["Sex"]])
X_test_embarked = ohe_emb.transform(X_test_emb)

In [40]:
print(X_train_sex.shape)
X_train_sex

(712, 2)

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [41]:
X_train_embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [42]:
X_train.head(2)

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S

In [44]:
# Now we will concatinate the columns
X_train_rem = X_train.drop(columns=["Sex", "Age", "Embarked"])
X_test_rem = X_test.drop(columns=["Sex", "Age", "Embarked"])

In [47]:
X_train_transformed = np.concatenate((X_train_rem,X_train_sex, X_train_age, X_train_embarked), axis = 1)
X_test_transformed = np.concatenate((X_test_rem,X_test_sex, X_test_age, X_test_embarked), axis = 1)

In [49]:
X_train_transformed.shape

(712, 10)

In [50]:
X_test_transformed.shape

(179, 10)

In [52]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed, y_train)

DecisionTreeClassifier()

In [53]:
y_pred = clf.predict(X_test_transformed)

In [54]:
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1], dtype=int64)

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7653631284916201

In [57]:
import pickle

In [58]:
pickle.dump(ohe_sex , open("ohe_sex.pkl", "wb"))
pickle.dump(ohe_emb, open("ohe_emb.pkl","wb"))
pickle.dump(clf, open("clf.pkl", "wb"))