In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("amazon_baby.csv")

In [3]:
df.shape

(183531, 3)

In [4]:
df.head()

,name,review,rating
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183531 entries, 0 to 183530
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   name    183213 non-null  object
 1   review  182702 non-null  object
 2   rating  183531 non-null  int64
dtypes: int64(1), object(2)
memory usage: 4.2+ MB

In [6]:
df.isnull().sum()

name      318
review    829
rating      0
dtype: int64

In [7]:
df1 = df.copy()

In [9]:
183531 - 182384

1147

In [11]:
df1.dropna(inplace=True)

In [12]:
df1.shape

(182384, 3)

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 182384 entries, 0 to 183530
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   name    182384 non-null  object
 1   review  182384 non-null  object
 2   rating  182384 non-null  int64
dtypes: int64(1), object(2)
memory usage: 5.6+ MB

In [14]:
df1.isnull().sum()

name      0
review    0
rating    0
dtype: int64

In [16]:
df.iloc[1,:]

name                                  Planetwise Wipe Pouch
review    it came early and was not disappointed. i love...
rating                                                    5
Name: 1, dtype: object

In [23]:
three_rating = df1[df1["rating"] == 3]

In [24]:
three_rating.shape

(16705, 3)

In [25]:
182384 - 16705

165679

In [18]:
df1[df1["rating"] != 3]

,name,review,rating
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5
5,Stop Pacifier Sucking without tears with Thumb...,"When the Binky Fairy came to our house, we did...",5
...,...,...,...
183526,Baby Teething Necklace for Mom Pretty Donut Sh...,Such a great idea! very handy to have and look...,5
183527,Baby Teething Necklace for Mom Pretty Donut Sh...,This product rocks! It is a great blend of fu...,5
183528,Abstract 2 PK Baby / Toddler Training Cup (Pink),This item looks great and cool for my kids.......,5
183529,"Baby Food Freezer Tray - Bacteria Resistant, B...",I am extremely happy with this product. I have...,5
183530,Best 2 Pack Baby Car Shade for Kids - Window S...,I love this product very mush . I have bought ...,5

In [26]:
df1 = df1[df1["rating"] != 3]

In [27]:
df1.shape

(165679, 3)