In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("play_tennis.csv")

In [3]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
df.drop(columns=["day"], inplace=True)

In [7]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [6]:
df.shape

(14, 5)

In [8]:
# problem 1

# outlook = "Sunny", temp = "Hot", humidity = "High", wind = "weak"
# play or No play

In [11]:
# solution 

# P(Yes | Sunny, Hot, High,	Weak) = P (Sunny|Yes) * P(Hot|Yes) * P(High|Yes) * P(Weak|Yes) * P(Yes)

# P(No | Sunny, Hot, High,	Weak) = P (Sunny|No) * P(Hot|No) * P(High|No) * P(Weak|No) * P(No)

# Compare and decide using the maximum a posteriori rule

In [12]:
# training

# lookup table {dictionary}

# testing

In [13]:
# P(Yes)
# P(No)

In [14]:
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [15]:
py = 9/14
pn = 5/14

In [16]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [17]:
# outlook

pd.crosstab(df["outlook"], df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [18]:
pon = 0
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [19]:
# temp

pd.crosstab(df["temp"], df["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [20]:
pcooln = 1/5
photn = 2/5
pmildn = 2/5

pcooly = 3/9
photy = 2/9
pmildy = 4/9

In [21]:
# Humidity

pd.crosstab(df["humidity"], df["play"])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
phighn = 4/5
pnormaln = 1/5

phighy = 3/9
pnormaly = 6/9

In [23]:
# wind

pd.crosstab(df["wind"], df["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [24]:
pstrongn = 3/5
pweakn = 2/5

pstrongy = 3/9
pweaky = 6/9

In [25]:
# problem 1

# outlook = "Sunny", temp = "Hot", humidity = "High", wind = "weak"
# play or No play

pyes = py * psy * photy * phighy * pweaky
print(pyes)

0.007054673721340388

In [26]:
pno = pn * psn * photn * phighn * pweakn
print(pno)

0.02742857142857143

In [27]:
# pno > pyes
# No Play