In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("customer.csv")

In [3]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
# In Encoding categorical data 
# We have two types of data
# 1. Numerical data
# 2. Categorical data

# And we have two types of categorical data
# 1. Nominal data (With this data we use One Hot Encodingg to encode this data.)
# 2. Ordinal data (With this data we use Ordinal encoding with the features and label encoding with the label(target) column.)

# in above data 
# age > numerical column
# gender > Nominal Categorical column
# review > Ordinal "" column
# education > Ordinal "" column
# purchased > Nominal "" column

In [6]:
df1 = df.iloc[:, 2:]

In [38]:
df1.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [5]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df1.drop("purchased", axis = 1), df1["purchased"], test_size = 0.2, random_state=0)

In [26]:
X_train.head()

     review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School

# Ordinal Encoding

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
oe = OrdinalEncoder(categories = [["Poor", "Average", "Good"], ["School", "UG", "PG"]])

In [22]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [23]:
X_train_tran = oe.transform(X_train)
X_test_tran = oe.transform(X_test)

In [24]:
X_train_tran

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [27]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoding

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le = LabelEncoder()

In [31]:
le.fit(y_train)

LabelEncoder()

In [32]:
y_train_tran = le.transform(y_train)
y_test_tran = le.transform(y_test)

In [33]:
y_train_tran

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [36]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [40]:
df.iloc[30:36, 2:]

     review education purchased
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes